### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by kgChem** [mcs07/PubChemPy#33]
Running this code from the [documentation](https://pubchempy.readthedocs.io/en/stable/guide/searching.html):

`pcp.get_compounds('CC', searchtype='superstructure', listkey_count=3)`

Generates the following error:

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "c:\Python27\lib\site-packages\pubchempy.py", line 124, in get_compounds
>     results = get_json(identifier, namespace, searchtype=searchtype, **kwargs)
>   File "c:\Python27\lib\site-packages\pubchempy.py", line 109, in get_json
>     return json.loads(get(identifier, namespace, domain, operation, 'JSON', sear
> chtype, **kwargs).decode())
>   File "c:\Python27\lib\site-packages\pubchempy.py", line 90, in get
>     response = request(identifier, namespace, domain, None, 'JSON', searchtype,
> **kwargs).read()
>   File "c:\Python27\lib\site-packages\pubchempy.py", line 84, in request
>     raise PubChemHTTPError(e)
>   File "c:\Python27\lib\site-packages\pubchempy.py", line 1089, in __init__
>     raise BadRequestError(self.msg)
> pubchempy.BadRequestError: 'Bad Request'

This preceding example from the same page works without error:
```
>>> pcp.get_compounds('Aspirin', 'name', record_type='3d')
[Compound(2244)]
>>>
```

**Comment by codeprimate123** [comment]
same issue here

**Comment by musexplorex** [comment]
Great, thanks for your work and your reply!

**Comment by DivyanshAgrawal22** [comment]
Hey @mcs07, really thanks for your work, I was looking for something which could give me the properties of the compounds using the SMILES notation. I tried using the `get_properties` function using the namespace as 'smiles' but I got the same error of BadRequestError. Is there any unique for every user through which we need to call the API to this library or what? I can't really understand as to why this error pops up, the procedure is pretty simple!! Please let me know if you could help me this query...

Regards
Divyansh

**Comment by subramanianramajayam** [comment]
sometimes props = pcp.get_properties([]) gives the results without much ado.Many times it fails to respond.

**Comment by ZiyuFanCSU** [comment]
@DivyanshAgrawal22 Have you solved this problem？
